### ISSUE TITLE
Please update cocoapods

### ISSUE THREAD

**Issue by ghost** [dariopellegrini/DPRadialMenu#3]
DPRadialMenu in Github is newer than Cocoapods.
There isn't important feature in Cocoapods.

**Comment by paradoxally** [comment]
Simply add the following line to your Podfile:

`pod 'DPRadialMenu', :git => 'https://github.com/dariopellegrini/DPRadialMenu.git'`

It will use the latest commit in the repo instead of the Cocoapods version.

Hope this helps.
